version: "3.9"
services:
  postgres:
      image: postgres
      container_name: keycloak-db
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
  keycloak:
      image: quay.io/keycloak/keycloak:24.0.2
      container_name: keycloak-1
      command:
        - start-dev
      volumes:
        - ./providers:/opt/keycloak/providers:z
      environment:
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_DB: postgres
        KC_HOSTNAME: localhost
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "8080:8080"
      depends_on:
        - postgres

volumes:
  postgres_data:
      driver: local