version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak-server
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev'
